/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CloseObligation
 * @category generated
 */
export type CloseObligationInstructionArgs = {
  bump: number
}
/**
 * @category Instructions
 * @category CloseObligation
 * @category generated
 */
export const closeObligationStruct = new beet.BeetArgsStruct<
  CloseObligationInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
  ],
  'CloseObligationInstructionArgs',
)
/**
 * Accounts required by the _closeObligation_ instruction
 *
 * @property [] market
 * @property [] marketAuthority
 * @property [_writable_, **signer**] owner
 * @property [_writable_] obligation
 * @category Instructions
 * @category CloseObligation
 * @category generated
 */
export type CloseObligationInstructionAccounts = {
  market: web3.PublicKey
  marketAuthority: web3.PublicKey
  owner: web3.PublicKey
  obligation: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const closeObligationInstructionDiscriminator = [
  178, 182, 18, 237, 158, 158, 51, 124,
]

/**
 * Creates a _CloseObligation_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CloseObligation
 * @category generated
 */
export function createCloseObligationInstruction(
  accounts: CloseObligationInstructionAccounts,
  args: CloseObligationInstructionArgs,
  programId = new web3.PublicKey('JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU'),
) {
  const [data] = closeObligationStruct.serialize({
    instructionDiscriminator: closeObligationInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.market,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.marketAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.owner,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.obligation,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
