/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CloseDepositAccount
 * @category generated
 */
export type CloseDepositAccountInstructionArgs = {
  bump: number
}
/**
 * @category Instructions
 * @category CloseDepositAccount
 * @category generated
 */
export const closeDepositAccountStruct = new beet.BeetArgsStruct<
  CloseDepositAccountInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
  ],
  'CloseDepositAccountInstructionArgs',
)
/**
 * Accounts required by the _closeDepositAccount_ instruction
 *
 * @property [] market
 * @property [] marketAuthority
 * @property [_writable_] reserve
 * @property [_writable_] vault
 * @property [_writable_] depositNoteMint
 * @property [_writable_, **signer**] depositor
 * @property [_writable_] depositAccount
 * @property [_writable_] receiverAccount
 * @category Instructions
 * @category CloseDepositAccount
 * @category generated
 */
export type CloseDepositAccountInstructionAccounts = {
  market: web3.PublicKey
  marketAuthority: web3.PublicKey
  reserve: web3.PublicKey
  vault: web3.PublicKey
  depositNoteMint: web3.PublicKey
  depositor: web3.PublicKey
  depositAccount: web3.PublicKey
  receiverAccount: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const closeDepositAccountInstructionDiscriminator = [
  152, 6, 13, 164, 50, 219, 225, 43,
]

/**
 * Creates a _CloseDepositAccount_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CloseDepositAccount
 * @category generated
 */
export function createCloseDepositAccountInstruction(
  accounts: CloseDepositAccountInstructionAccounts,
  args: CloseDepositAccountInstructionArgs,
  programId = new web3.PublicKey('JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU'),
) {
  const [data] = closeDepositAccountStruct.serialize({
    instructionDiscriminator: closeDepositAccountInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.market,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.marketAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.reserve,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.depositNoteMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.depositor,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.depositAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.receiverAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
