/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CloseCollateralAccount
 * @category generated
 */
export type CloseCollateralAccountInstructionArgs = {
  bump: number
}
/**
 * @category Instructions
 * @category CloseCollateralAccount
 * @category generated
 */
export const closeCollateralAccountStruct = new beet.BeetArgsStruct<
  CloseCollateralAccountInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
  ],
  'CloseCollateralAccountInstructionArgs',
)
/**
 * Accounts required by the _closeCollateralAccount_ instruction
 *
 * @property [] market
 * @property [] marketAuthority
 * @property [_writable_] obligation
 * @property [_writable_, **signer**] owner
 * @property [_writable_] collateralAccount
 * @property [_writable_] depositAccount
 * @category Instructions
 * @category CloseCollateralAccount
 * @category generated
 */
export type CloseCollateralAccountInstructionAccounts = {
  market: web3.PublicKey
  marketAuthority: web3.PublicKey
  obligation: web3.PublicKey
  owner: web3.PublicKey
  collateralAccount: web3.PublicKey
  depositAccount: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const closeCollateralAccountInstructionDiscriminator = [
  106, 184, 133, 142, 131, 191, 224, 29,
]

/**
 * Creates a _CloseCollateralAccount_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CloseCollateralAccount
 * @category generated
 */
export function createCloseCollateralAccountInstruction(
  accounts: CloseCollateralAccountInstructionAccounts,
  args: CloseCollateralAccountInstructionArgs,
  programId = new web3.PublicKey('JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU'),
) {
  const [data] = closeCollateralAccountStruct.serialize({
    instructionDiscriminator: closeCollateralAccountInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.market,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.marketAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.obligation,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.owner,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.collateralAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.depositAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
