/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import { Amount, amountBeet } from '../types/Amount.js'

/**
 * @category Instructions
 * @category DepositTokens
 * @category generated
 */
export type DepositTokensInstructionArgs = {
  amount: Amount
}
/**
 * @category Instructions
 * @category DepositTokens
 * @category generated
 */
export const depositTokensStruct = new beet.BeetArgsStruct<
  DepositTokensInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['amount', amountBeet],
  ],
  'DepositTokensInstructionArgs',
)
/**
 * Accounts required by the _depositTokens_ instruction
 *
 * @property [] market
 * @property [] marketAuthority
 * @property [_writable_] reserve
 * @property [_writable_] vault
 * @property [_writable_] depositNoteMint
 * @property [**signer**] depositor
 * @property [_writable_] depositNoteAccount
 * @property [_writable_] depositSource
 * @category Instructions
 * @category DepositTokens
 * @category generated
 */
export type DepositTokensInstructionAccounts = {
  market: web3.PublicKey
  marketAuthority: web3.PublicKey
  reserve: web3.PublicKey
  vault: web3.PublicKey
  depositNoteMint: web3.PublicKey
  depositor: web3.PublicKey
  depositNoteAccount: web3.PublicKey
  depositSource: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const depositTokensInstructionDiscriminator = [
  176, 83, 229, 18, 191, 143, 176, 150,
]

/**
 * Creates a _DepositTokens_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category DepositTokens
 * @category generated
 */
export function createDepositTokensInstruction(
  accounts: DepositTokensInstructionAccounts,
  args: DepositTokensInstructionArgs,
  programId = new web3.PublicKey('JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU'),
) {
  const [data] = depositTokensStruct.serialize({
    instructionDiscriminator: depositTokensInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.market,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.marketAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.reserve,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.depositNoteMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.depositor,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.depositNoteAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.depositSource,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
