/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category InitObligation
 * @category generated
 */
export type InitObligationInstructionArgs = {
  bump: number
}
/**
 * @category Instructions
 * @category InitObligation
 * @category generated
 */
export const initObligationStruct = new beet.BeetArgsStruct<
  InitObligationInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
  ],
  'InitObligationInstructionArgs',
)
/**
 * Accounts required by the _initObligation_ instruction
 *
 * @property [] market
 * @property [] marketAuthority
 * @property [_writable_, **signer**] borrower
 * @property [_writable_] obligation
 * @category Instructions
 * @category InitObligation
 * @category generated
 */
export type InitObligationInstructionAccounts = {
  market: web3.PublicKey
  marketAuthority: web3.PublicKey
  borrower: web3.PublicKey
  obligation: web3.PublicKey
  tokenProgram?: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const initObligationInstructionDiscriminator = [
  251, 10, 231, 76, 27, 11, 159, 96,
]

/**
 * Creates a _InitObligation_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category InitObligation
 * @category generated
 */
export function createInitObligationInstruction(
  accounts: InitObligationInstructionAccounts,
  args: InitObligationInstructionArgs,
  programId = new web3.PublicKey('JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU'),
) {
  const [data] = initObligationStruct.serialize({
    instructionDiscriminator: initObligationInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.market,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.marketAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.borrower,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.obligation,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
