/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'

/**
 * @category Instructions
 * @category InitMarket
 * @category generated
 */
export type InitMarketInstructionArgs = {
  owner: web3.PublicKey
  quoteCurrency: string
  quoteTokenMint: web3.PublicKey
}
/**
 * @category Instructions
 * @category InitMarket
 * @category generated
 */
export const initMarketStruct = new beet.FixableBeetArgsStruct<
  InitMarketInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['owner', beetSolana.publicKey],
    ['quoteCurrency', beet.utf8String],
    ['quoteTokenMint', beetSolana.publicKey],
  ],
  'InitMarketInstructionArgs',
)
/**
 * Accounts required by the _initMarket_ instruction
 *
 * @property [_writable_] market
 * @category Instructions
 * @category InitMarket
 * @category generated
 */
export type InitMarketInstructionAccounts = {
  market: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const initMarketInstructionDiscriminator = [
  33, 253, 15, 116, 89, 25, 127, 236,
]

/**
 * Creates a _InitMarket_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category InitMarket
 * @category generated
 */
export function createInitMarketInstruction(
  accounts: InitMarketInstructionAccounts,
  args: InitMarketInstructionArgs,
  programId = new web3.PublicKey('JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU'),
) {
  const [data] = initMarketStruct.serialize({
    instructionDiscriminator: initMarketInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.market,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
