/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'

/**
 * @category Instructions
 * @category SetMarketOwner
 * @category generated
 */
export type SetMarketOwnerInstructionArgs = {
  newOwner: web3.PublicKey
}
/**
 * @category Instructions
 * @category SetMarketOwner
 * @category generated
 */
export const setMarketOwnerStruct = new beet.BeetArgsStruct<
  SetMarketOwnerInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['newOwner', beetSolana.publicKey],
  ],
  'SetMarketOwnerInstructionArgs',
)
/**
 * Accounts required by the _setMarketOwner_ instruction
 *
 * @property [_writable_] market
 * @property [**signer**] owner
 * @category Instructions
 * @category SetMarketOwner
 * @category generated
 */
export type SetMarketOwnerInstructionAccounts = {
  market: web3.PublicKey
  owner: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const setMarketOwnerInstructionDiscriminator = [
  166, 195, 167, 232, 32, 198, 184, 182,
]

/**
 * Creates a _SetMarketOwner_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category SetMarketOwner
 * @category generated
 */
export function createSetMarketOwnerInstruction(
  accounts: SetMarketOwnerInstructionAccounts,
  args: SetMarketOwnerInstructionArgs,
  programId = new web3.PublicKey('JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU'),
) {
  const [data] = setMarketOwnerStruct.serialize({
    instructionDiscriminator: setMarketOwnerInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.market,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.owner,
      isWritable: false,
      isSigner: true,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
