/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category SetMarketFlags
 * @category generated
 */
export type SetMarketFlagsInstructionArgs = {
  flags: beet.bignum
}
/**
 * @category Instructions
 * @category SetMarketFlags
 * @category generated
 */
export const setMarketFlagsStruct = new beet.BeetArgsStruct<
  SetMarketFlagsInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['flags', beet.u64],
  ],
  'SetMarketFlagsInstructionArgs',
)
/**
 * Accounts required by the _setMarketFlags_ instruction
 *
 * @property [_writable_] market
 * @property [**signer**] owner
 * @category Instructions
 * @category SetMarketFlags
 * @category generated
 */
export type SetMarketFlagsInstructionAccounts = {
  market: web3.PublicKey
  owner: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const setMarketFlagsInstructionDiscriminator = [
  73, 138, 236, 76, 82, 179, 94, 155,
]

/**
 * Creates a _SetMarketFlags_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category SetMarketFlags
 * @category generated
 */
export function createSetMarketFlagsInstruction(
  accounts: SetMarketFlagsInstructionAccounts,
  args: SetMarketFlagsInstructionArgs,
  programId = new web3.PublicKey('JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU'),
) {
  const [data] = setMarketFlagsStruct.serialize({
    instructionDiscriminator: setMarketFlagsInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.market,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.owner,
      isWritable: false,
      isSigner: true,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
