/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { AmountUnits, amountUnitsBeet } from './AmountUnits.js'
export type Amount = {
  units: AmountUnits
  value: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const amountBeet = new beet.BeetArgsStruct<Amount>(
  [
    ['units', amountUnitsBeet],
    ['value', beet.u64],
  ],
  'Amount',
)
