/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type InitReserveBumpSeeds = {
  vault: number
  feeNoteVault: number
  dexOpenOrders: number
  dexSwapTokens: number
  depositNoteMint: number
  loanNoteMint: number
}

/**
 * @category userTypes
 * @category generated
 */
export const initReserveBumpSeedsBeet =
  new beet.BeetArgsStruct<InitReserveBumpSeeds>(
    [
      ['vault', beet.u8],
      ['feeNoteVault', beet.u8],
      ['dexOpenOrders', beet.u8],
      ['dexSwapTokens', beet.u8],
      ['depositNoteMint', beet.u8],
      ['loanNoteMint', beet.u8],
    ],
    'InitReserveBumpSeeds',
  )
