/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type ReserveConfig = {
  utilizationRate1: number
  utilizationRate2: number
  borrowRate0: number
  borrowRate1: number
  borrowRate2: number
  borrowRate3: number
  minCollateralRatio: number
  liquidationPremium: number
  manageFeeCollectionThreshold: beet.bignum
  manageFeeRate: number
  loanOriginationFee: number
  reserved0: number
  confidenceThreshold: number
  liquidationDexTradeMax: beet.bignum
  reserved1: number[] /* size: 24 */
}

/**
 * @category userTypes
 * @category generated
 */
export const reserveConfigBeet = new beet.BeetArgsStruct<ReserveConfig>(
  [
    ['utilizationRate1', beet.u16],
    ['utilizationRate2', beet.u16],
    ['borrowRate0', beet.u16],
    ['borrowRate1', beet.u16],
    ['borrowRate2', beet.u16],
    ['borrowRate3', beet.u16],
    ['minCollateralRatio', beet.u16],
    ['liquidationPremium', beet.u16],
    ['manageFeeCollectionThreshold', beet.u64],
    ['manageFeeRate', beet.u16],
    ['loanOriginationFee', beet.u16],
    ['reserved0', beet.u16],
    ['confidenceThreshold', beet.u16],
    ['liquidationDexTradeMax', beet.u64],
    ['reserved1', beet.uniformFixedSizeArray(beet.u8, 24)],
  ],
  'ReserveConfig',
)
